# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJEdVlICQKJT1KhI0G5xYtct5iHf27C4
"""

# daily_report.py
import os
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo
import pandas as pd
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

CORREO_ORIGEN = os.environ["CORREO_ORIGEN"]
CONTRASENA = os.environ["CONTRASENA"]
def obtener_destinatarios():
    raw = os.environ.get("DESTINATARIOS") or os.environ.get("DESTINATARIO")
    if not raw:
        raise RuntimeError("No se encontró DESTINATARIOS ni DESTINATARIO")
    parts = [p.strip() for p in raw.replace(";", ",").split(",") if p.strip()]
    return parts
DESTINATARIOS = obtener_destinatarios()

TZ = ZoneInfo("America/Santiago")

def read_station_csv(station_id):
    path = f"data/{station_id}.csv"
    if not os.path.exists(path):
        return None
    df = pd.read_csv(path, parse_dates=["timestamp"])
    # Asegurar tz-aware
    if df["timestamp"].dt.tz is None:
        df["timestamp"] = df["timestamp"].dt.tz_localize("UTC").dt.tz_convert(TZ)
    else:
        df["timestamp"] = df["timestamp"].dt.tz_convert(TZ)
    df = df.set_index("timestamp").sort_index()
    return df

def hourly_stats_for_date(df, date_local):
    """date_local is a date (datetime.date) in TZ: compute stats for that date 00:00 -> 23:59"""
    start = datetime(date_local.year, date_local.month, date_local.day, tzinfo=TZ)
    end = start + timedelta(days=1)
    df_day = df.loc[(df.index >= start) & (df.index < end)]
    if df_day.empty:
        return None
    hourly = df_day["wind_kt"].resample("H").agg(["min", "max", "mean"])
    # media movil de la media horaria (window=3)
    hourly["mean_ma3"] = hourly["mean"].rolling(window=3, min_periods=1).mean()
    return hourly

def build_report_for_date(date_local):
    stations = ["330021", "330114"]
    parts = []
    for s in stations:
        df = read_station_csv(s)
        parts.append(f"--- Estación {s} ---")
        if df is None:
            parts.append("No hay datos (archivo faltante).")
            continue
        stats = hourly_stats_for_date(df, date_local)
        if stats is None:
            parts.append("No se encontraron registros para la fecha.")
            continue
        parts.append("Hora (local) | min(kt) | max(kt) | mean(kt) | mean_MA3(kt)")
        for idx, row in stats.iterrows():
            hour_label = idx.strftime("%Y-%m-%d %H:%M")
            parts.append(f"{hour_label} | {row['min']:.1f} | {row['max']:.1f} | {row['mean']:.2f} | {row['mean_ma3']:.2f}")
    return "\n".join(parts)

def enviar_correo(subject, body):
    msg = MIMEMultipart()
    msg["From"] = CORREO_ORIGEN
    msg["To"] = ", ".join(DESTINATARIOS)
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))
    s = smtplib.SMTP("smtp.gmail.com", 587)
    s.starttls()
    s.login(CORREO_ORIGEN, CONTRASENA)
    s.sendmail(CORREO_ORIGEN, DESTINATARIOS, msg.as_string())
    s.quit()

if __name__ == "__main__":
    now = datetime.now(TZ)
    # generar informe del día anterior (fecha local)
    report_date = (now - timedelta(days=1)).date()
    body = f"Informe diario para la fecha {report_date.isoformat()} (horas locales, America/Santiago)\n\n"
    body += build_report_for_date(report_date)
    subject = f"Informe diario de viento - {report_date.isoformat()}"
    enviar_correo(subject, body)
    print("Informe diario enviado.")